/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "../drizzle-zero.config";

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    channelMembers: {
      name: "channelMembers",
      columns: {
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "userId"
          >,
          serverName: "user_id",
        },
        channelId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "channelId"
          >,
          serverName: "channel_id",
        },
        isHidden: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "isHidden"
          >,
          serverName: "is_hiddem",
        },
        isMuted: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "isMuted"
          >,
          serverName: "is_muted",
        },
        lastSeenMessageId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "lastSeenMessageId"
          >,
          serverName: "last_seen_message_id",
        },
        notificationCount: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "notificationCount"
          >,
          serverName: "notification_count",
        },
        joinedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "channelMembers",
            "joinedAt"
          >,
          serverName: "joined_at",
        },
      },
      primaryKey: ["userId", "channelId"],
      serverName: "channel_members",
    },
    messages: {
      name: "messages",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "id"
          >,
        },
        content: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "content"
          >,
        },
        channelId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "channelId"
          >,
        },
        threadChannelId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "threadChannelId"
          >,
          serverName: "thread_channel_id",
        },
        authorId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "authorId"
          >,
          serverName: "author_id",
        },
        replyToMessageId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "replyToMessageId"
          >,
          serverName: "reply_to_message_id",
        },
        attachedFiles: {
          type: "json",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "attachedFiles"
          >,
          serverName: "attached_files",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "messages",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    pinnedMessages: {
      name: "pinnedMessages",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pinnedMessages",
            "id"
          >,
        },
        messageId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pinnedMessages",
            "messageId"
          >,
          serverName: "message_id",
        },
        channelId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "pinnedMessages",
            "channelId"
          >,
          serverName: "channel_id",
        },
      },
      primaryKey: ["id"],
      serverName: "pinned_messages",
    },
    reactions: {
      name: "reactions",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "reactions",
            "id"
          >,
        },
        messageId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "reactions",
            "messageId"
          >,
          serverName: "message_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "reactions",
            "userId"
          >,
          serverName: "user_id",
        },
        emoji: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "reactions",
            "emoji"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "reactions",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    server: {
      name: "server",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "id"
          >,
        },
        ownerId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "ownerId"
          >,
          serverName: "owner_id",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "name"
          >,
        },
        slug: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "slug"
          >,
        },
        imageUrl: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "imageUrl"
          >,
          serverName: "image_url",
        },
        type: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "type"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "server",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    serverChannels: {
      name: "serverChannels",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "id"
          >,
        },
        serverId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "serverId"
          >,
          serverName: "server_id",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "name"
          >,
        },
        channelType: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "channelType"
          >,
          serverName: "channel_type",
        },
        parentChannelId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "parentChannelId"
          >,
          serverName: "parent_channel_id",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverChannels",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "server_channels",
    },
    serverMembers: {
      name: "serverMembers",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverMembers",
            "id"
          >,
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverMembers",
            "userId"
          >,
          serverName: "user_id",
        },
        serverId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverMembers",
            "serverId"
          >,
          serverName: "server_id",
        },
        role: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverMembers",
            "role"
          >,
        },
        joinedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "serverMembers",
            "joinedAt"
          >,
          serverName: "joined_at",
        },
      },
      primaryKey: ["id"],
      serverName: "server_members",
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "id"
          >,
        },
        displayName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "displayName"
          >,
          serverName: "display_name",
        },
        tag: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "tag"
          >,
        },
        avatarUrl: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "avatarUrl"
          >,
          serverName: "avatar_url",
        },
        lastSeen: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "lastSeen"
          >,
          serverName: "last_seen",
        },
        status: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            "users",
            "status"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "user",
    },
  },
  relationships: {
    server: {
      users: [
        {
          sourceField: ["id"],
          destField: ["serverId"],
          destSchema: "serverMembers",
          cardinality: "many",
        },
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "many",
        },
      ],
      owner: [
        {
          sourceField: ["ownerId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      members: [
        {
          sourceField: ["id"],
          destField: ["serverId"],
          destSchema: "serverMembers",
          cardinality: "many",
        },
      ],
      channels: [
        {
          sourceField: ["id"],
          destField: ["serverId"],
          destSchema: "serverChannels",
          cardinality: "many",
        },
      ],
    },
    users: {
      servers: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "serverMembers",
          cardinality: "many",
        },
        {
          sourceField: ["serverId"],
          destField: ["id"],
          destSchema: "server",
          cardinality: "many",
        },
      ],
      serverChannels: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "channelMembers",
          cardinality: "many",
        },
        {
          sourceField: ["channelId"],
          destField: ["id"],
          destSchema: "serverChannels",
          cardinality: "many",
        },
      ],
      serversOwned: [
        {
          sourceField: ["id"],
          destField: ["ownerId"],
          destSchema: "server",
          cardinality: "many",
        },
      ],
      serverMemberships: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "serverMembers",
          cardinality: "many",
        },
      ],
      channelMemberships: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "channelMembers",
          cardinality: "many",
        },
      ],
      messagesAuthored: [
        {
          sourceField: ["id"],
          destField: ["authorId"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
      reactionsAdded: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "reactions",
          cardinality: "many",
        },
      ],
    },
    serverChannels: {
      users: [
        {
          sourceField: ["id"],
          destField: ["channelId"],
          destSchema: "channelMembers",
          cardinality: "many",
        },
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "many",
        },
      ],
      server: [
        {
          sourceField: ["serverId"],
          destField: ["id"],
          destSchema: "server",
          cardinality: "one",
        },
      ],
      parentChannel: [
        {
          sourceField: ["parentChannelId"],
          destField: ["id"],
          destSchema: "serverChannels",
          cardinality: "one",
        },
      ],
      members: [
        {
          sourceField: ["id"],
          destField: ["channelId"],
          destSchema: "channelMembers",
          cardinality: "many",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["channelId"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
      pinnedMessages: [
        {
          sourceField: ["id"],
          destField: ["channelId"],
          destSchema: "pinnedMessages",
          cardinality: "many",
        },
      ],
    },
    channelMembers: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      channel: [
        {
          sourceField: ["channelId"],
          destField: ["id"],
          destSchema: "serverChannels",
          cardinality: "one",
        },
      ],
    },
    messages: {
      channel: [
        {
          sourceField: ["channelId"],
          destField: ["id"],
          destSchema: "serverChannels",
          cardinality: "one",
        },
      ],
      threadChannel: [
        {
          sourceField: ["threadChannelId"],
          destField: ["id"],
          destSchema: "serverChannels",
          cardinality: "one",
        },
      ],
      author: [
        {
          sourceField: ["authorId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      replyToMessage: [
        {
          sourceField: ["replyToMessageId"],
          destField: ["id"],
          destSchema: "messages",
          cardinality: "one",
        },
      ],
      replies: [
        {
          sourceField: ["id"],
          destField: ["replyToMessageId"],
          destSchema: "messages",
          cardinality: "many",
        },
      ],
      pinnedInChannels: [
        {
          sourceField: ["id"],
          destField: ["messageId"],
          destSchema: "pinnedMessages",
          cardinality: "many",
        },
      ],
      reactions: [
        {
          sourceField: ["id"],
          destField: ["messageId"],
          destSchema: "reactions",
          cardinality: "many",
        },
      ],
    },
    pinnedMessages: {
      message: [
        {
          sourceField: ["messageId"],
          destField: ["id"],
          destSchema: "messages",
          cardinality: "one",
        },
      ],
      channel: [
        {
          sourceField: ["channelId"],
          destField: ["id"],
          destSchema: "serverChannels",
          cardinality: "one",
        },
      ],
    },
    reactions: {
      message: [
        {
          sourceField: ["messageId"],
          destField: ["id"],
          destSchema: "messages",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
    },
    serverMembers: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "users",
          cardinality: "one",
        },
      ],
      server: [
        {
          sourceField: ["serverId"],
          destField: ["id"],
          destSchema: "server",
          cardinality: "one",
        },
      ],
    },
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
