/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { default as DrizzleConfigSchema } from "../../drizzle-zero.config"

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
	tables: {
		channelMembers: {
			name: "channelMembers",
			columns: {
				userId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["channelMembers"]["columns"]["userId"]["customType"],
					serverName: "user_id",
				},
				channelId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["channelMembers"]["columns"]["channelId"]["customType"],
					serverName: "channel_id",
				},
				joinedAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["channelMembers"]["columns"]["joinedAt"]["customType"],
					serverName: "joined_at",
				},
			},
			primaryKey: ["userId", "channelId"],
			serverName: "channel_members",
		},
		messages: {
			name: "messages",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["id"]["customType"],
				},
				content: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["content"]["customType"],
				},
				channelId: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["channelId"]["customType"],
				},
				authorId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["authorId"]["customType"],
					serverName: "author_id",
				},
				parentMessageId: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["parentMessageId"]["customType"],
					serverName: "parent_message_id",
				},
				replyToMessageId: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["replyToMessageId"]["customType"],
					serverName: "reply_to_message_id",
				},
				attachedFiles: {
					type: "json",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["attachedFiles"]["customType"],
					serverName: "attached_files",
				},
				createdAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["createdAt"]["customType"],
					serverName: "created_at",
				},
				updatedAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["messages"]["columns"]["updatedAt"]["customType"],
					serverName: "updated_at",
				},
			},
			primaryKey: ["id"],
		},
		pinnedMessages: {
			name: "pinnedMessages",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["pinnedMessages"]["columns"]["id"]["customType"],
				},
				messageId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["pinnedMessages"]["columns"]["messageId"]["customType"],
					serverName: "message_id",
				},
				channelId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["pinnedMessages"]["columns"]["channelId"]["customType"],
					serverName: "channel_id",
				},
			},
			primaryKey: ["id"],
			serverName: "pinned_messages",
		},
		reactions: {
			name: "reactions",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["reactions"]["columns"]["id"]["customType"],
				},
				messageId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["reactions"]["columns"]["messageId"]["customType"],
					serverName: "message_id",
				},
				userId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["reactions"]["columns"]["userId"]["customType"],
					serverName: "user_id",
				},
				emoji: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["reactions"]["columns"]["emoji"]["customType"],
				},
				createdAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["reactions"]["columns"]["createdAt"]["customType"],
					serverName: "created_at",
				},
			},
			primaryKey: ["id"],
		},
		server: {
			name: "server",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["id"]["customType"],
				},
				ownerId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["ownerId"]["customType"],
					serverName: "owner_id",
				},
				name: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["name"]["customType"],
				},
				slug: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["slug"]["customType"],
				},
				imageUrl: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["imageUrl"]["customType"],
					serverName: "image_url",
				},
				type: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["type"]["customType"],
				},
				createdAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["createdAt"]["customType"],
					serverName: "created_at",
				},
				updatedAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["server"]["columns"]["updatedAt"]["customType"],
					serverName: "updated_at",
				},
			},
			primaryKey: ["id"],
		},
		serverChannels: {
			name: "serverChannels",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverChannels"]["columns"]["id"]["customType"],
				},
				serverId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverChannels"]["columns"]["serverId"]["customType"],
					serverName: "server_id",
				},
				name: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverChannels"]["columns"]["name"]["customType"],
				},
				channelType: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverChannels"]["columns"]["channelType"]["customType"],
					serverName: "channel_type",
				},
				createdAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverChannels"]["columns"]["createdAt"]["customType"],
					serverName: "created_at",
				},
				updatedAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverChannels"]["columns"]["updatedAt"]["customType"],
					serverName: "updated_at",
				},
			},
			primaryKey: ["id"],
			serverName: "server_channels",
		},
		serverMembers: {
			name: "serverMembers",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverMembers"]["columns"]["id"]["customType"],
				},
				userId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverMembers"]["columns"]["userId"]["customType"],
					serverName: "user_id",
				},
				serverId: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverMembers"]["columns"]["serverId"]["customType"],
					serverName: "server_id",
				},
				role: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverMembers"]["columns"]["role"]["customType"],
				},
				joinedAt: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["serverMembers"]["columns"]["joinedAt"]["customType"],
					serverName: "joined_at",
				},
			},
			primaryKey: ["id"],
			serverName: "server_members",
		},
		users: {
			name: "users",
			columns: {
				id: {
					type: "string",
					optional: false,
					customType: null as (typeof DrizzleConfigSchema)["tables"]["users"]["columns"]["id"]["customType"],
				},
				displayName: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["users"]["columns"]["displayName"]["customType"],
					serverName: "display_name",
				},
				tag: {
					type: "string",
					optional: false,
					customType: null as (typeof DrizzleConfigSchema)["tables"]["users"]["columns"]["tag"]["customType"],
				},
				avatarUrl: {
					type: "string",
					optional: false,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["users"]["columns"]["avatarUrl"]["customType"],
					serverName: "avatar_url",
				},
				lastSeen: {
					type: "number",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["users"]["columns"]["lastSeen"]["customType"],
					serverName: "last_seen",
				},
				status: {
					type: "string",
					optional: true,
					customType:
						null as (typeof DrizzleConfigSchema)["tables"]["users"]["columns"]["status"]["customType"],
				},
			},
			primaryKey: ["id"],
			serverName: "user",
		},
	},
	relationships: {
		server: {
			users: [
				{
					sourceField: ["id"],
					destField: ["serverId"],
					destSchema: "serverMembers",
					cardinality: "many",
				},
				{
					sourceField: ["userId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "many",
				},
			],
			owner: [
				{
					sourceField: ["ownerId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "one",
				},
			],
			members: [
				{
					sourceField: ["id"],
					destField: ["serverId"],
					destSchema: "serverMembers",
					cardinality: "many",
				},
			],
			channels: [
				{
					sourceField: ["id"],
					destField: ["serverId"],
					destSchema: "serverChannels",
					cardinality: "many",
				},
			],
		},
		users: {
			servers: [
				{
					sourceField: ["id"],
					destField: ["userId"],
					destSchema: "serverMembers",
					cardinality: "many",
				},
				{
					sourceField: ["serverId"],
					destField: ["id"],
					destSchema: "server",
					cardinality: "many",
				},
			],
			serverChannels: [
				{
					sourceField: ["id"],
					destField: ["userId"],
					destSchema: "channelMembers",
					cardinality: "many",
				},
				{
					sourceField: ["channelId"],
					destField: ["id"],
					destSchema: "serverChannels",
					cardinality: "many",
				},
			],
			serversOwned: [
				{
					sourceField: ["id"],
					destField: ["ownerId"],
					destSchema: "server",
					cardinality: "many",
				},
			],
			serverMemberships: [
				{
					sourceField: ["id"],
					destField: ["userId"],
					destSchema: "serverMembers",
					cardinality: "many",
				},
			],
			channelMemberships: [
				{
					sourceField: ["id"],
					destField: ["userId"],
					destSchema: "channelMembers",
					cardinality: "many",
				},
			],
			messagesAuthored: [
				{
					sourceField: ["id"],
					destField: ["authorId"],
					destSchema: "messages",
					cardinality: "many",
				},
			],
			reactionsAdded: [
				{
					sourceField: ["id"],
					destField: ["userId"],
					destSchema: "reactions",
					cardinality: "many",
				},
			],
		},
		serverChannels: {
			users: [
				{
					sourceField: ["id"],
					destField: ["channelId"],
					destSchema: "channelMembers",
					cardinality: "many",
				},
				{
					sourceField: ["userId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "many",
				},
			],
			server: [
				{
					sourceField: ["serverId"],
					destField: ["id"],
					destSchema: "server",
					cardinality: "one",
				},
			],
			members: [
				{
					sourceField: ["id"],
					destField: ["channelId"],
					destSchema: "channelMembers",
					cardinality: "many",
				},
			],
			messages: [
				{
					sourceField: ["id"],
					destField: ["channelId"],
					destSchema: "messages",
					cardinality: "many",
				},
			],
			pinnedMessages: [
				{
					sourceField: ["id"],
					destField: ["channelId"],
					destSchema: "pinnedMessages",
					cardinality: "many",
				},
			],
		},
		channelMembers: {
			user: [
				{
					sourceField: ["userId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "one",
				},
			],
			channel: [
				{
					sourceField: ["channelId"],
					destField: ["id"],
					destSchema: "serverChannels",
					cardinality: "one",
				},
			],
		},
		messages: {
			channel: [
				{
					sourceField: ["channelId"],
					destField: ["id"],
					destSchema: "serverChannels",
					cardinality: "one",
				},
			],
			author: [
				{
					sourceField: ["authorId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "one",
				},
			],
			parentMessage: [
				{
					sourceField: ["parentMessageId"],
					destField: ["id"],
					destSchema: "messages",
					cardinality: "one",
				},
			],
			childMessages: [
				{
					sourceField: ["id"],
					destField: ["parentMessageId"],
					destSchema: "messages",
					cardinality: "many",
				},
			],
			replyToMessage: [
				{
					sourceField: ["replyToMessageId"],
					destField: ["id"],
					destSchema: "messages",
					cardinality: "one",
				},
			],
			replies: [
				{
					sourceField: ["id"],
					destField: ["replyToMessageId"],
					destSchema: "messages",
					cardinality: "many",
				},
			],
			pinnedInChannels: [
				{
					sourceField: ["id"],
					destField: ["messageId"],
					destSchema: "pinnedMessages",
					cardinality: "many",
				},
			],
			reactions: [
				{
					sourceField: ["id"],
					destField: ["messageId"],
					destSchema: "reactions",
					cardinality: "many",
				},
			],
		},
		pinnedMessages: {
			message: [
				{
					sourceField: ["messageId"],
					destField: ["id"],
					destSchema: "messages",
					cardinality: "one",
				},
			],
			channel: [
				{
					sourceField: ["channelId"],
					destField: ["id"],
					destSchema: "serverChannels",
					cardinality: "one",
				},
			],
		},
		reactions: {
			message: [
				{
					sourceField: ["messageId"],
					destField: ["id"],
					destSchema: "messages",
					cardinality: "one",
				},
			],
			user: [
				{
					sourceField: ["userId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "one",
				},
			],
		},
		serverMembers: {
			user: [
				{
					sourceField: ["userId"],
					destField: ["id"],
					destSchema: "users",
					cardinality: "one",
				},
			],
			server: [
				{
					sourceField: ["serverId"],
					destField: ["id"],
					destSchema: "server",
					cardinality: "one",
				},
			],
		},
	},
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
