/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ProtectedAppLayoutRouteImport } from './routes/_protected/_app/layout'
import { Route as ProtectedOnboardingIndexRouteImport } from './routes/_protected/onboarding/index'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/_app/index'
import { Route as ProtectedAppServerIdLayoutRouteImport } from './routes/_protected/_app/$serverId/layout'
import { Route as ProtectedAppServerIdIndexRouteImport } from './routes/_protected/_app/$serverId/index'
import { Route as ProtectedAppServerIdSettingsRouteImport } from './routes/_protected/_app/$serverId/settings'
import { Route as ProtectedAppServerIdBillingRouteImport } from './routes/_protected/_app/$serverId/billing'
import { Route as ProtectedAppServerIdProfileIdRouteImport } from './routes/_protected/_app/$serverId/profile/$id'
import { Route as ProtectedAppServerIdChatIdRouteImport } from './routes/_protected/_app/$serverId/chat/$id'

// Create/Update Routes

const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const ProtectedAppLayoutRoute = ProtectedAppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedOnboardingIndexRoute =
  ProtectedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAppLayoutRoute,
} as any)

const ProtectedAppServerIdLayoutRoute =
  ProtectedAppServerIdLayoutRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => ProtectedAppLayoutRoute,
  } as any)

const ProtectedAppServerIdIndexRoute =
  ProtectedAppServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAppServerIdLayoutRoute,
  } as any)

const ProtectedAppServerIdSettingsRoute =
  ProtectedAppServerIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedAppServerIdLayoutRoute,
  } as any)

const ProtectedAppServerIdBillingRoute =
  ProtectedAppServerIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedAppServerIdLayoutRoute,
  } as any)

const ProtectedAppServerIdProfileIdRoute =
  ProtectedAppServerIdProfileIdRouteImport.update({
    id: '/profile/$id',
    path: '/profile/$id',
    getParentRoute: () => ProtectedAppServerIdLayoutRoute,
  } as any)

const ProtectedAppServerIdChatIdRoute =
  ProtectedAppServerIdChatIdRouteImport.update({
    id: '/chat/$id',
    path: '/chat/$id',
    getParentRoute: () => ProtectedAppServerIdLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_app': {
      id: '/_protected/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedAppLayoutRouteImport
      parentRoute: typeof ProtectedLayoutRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRouteImport
    }
    '/_protected/_app/$serverId': {
      id: '/_protected/_app/$serverId'
      path: '/$serverId'
      fullPath: '/$serverId'
      preLoaderRoute: typeof ProtectedAppServerIdLayoutRouteImport
      parentRoute: typeof ProtectedAppLayoutRouteImport
    }
    '/_protected/_app/': {
      id: '/_protected/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedAppLayoutRouteImport
    }
    '/_protected/onboarding/': {
      id: '/_protected/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingIndexRouteImport
      parentRoute: typeof ProtectedLayoutRouteImport
    }
    '/_protected/_app/$serverId/billing': {
      id: '/_protected/_app/$serverId/billing'
      path: '/billing'
      fullPath: '/$serverId/billing'
      preLoaderRoute: typeof ProtectedAppServerIdBillingRouteImport
      parentRoute: typeof ProtectedAppServerIdLayoutRouteImport
    }
    '/_protected/_app/$serverId/settings': {
      id: '/_protected/_app/$serverId/settings'
      path: '/settings'
      fullPath: '/$serverId/settings'
      preLoaderRoute: typeof ProtectedAppServerIdSettingsRouteImport
      parentRoute: typeof ProtectedAppServerIdLayoutRouteImport
    }
    '/_protected/_app/$serverId/': {
      id: '/_protected/_app/$serverId/'
      path: '/'
      fullPath: '/$serverId/'
      preLoaderRoute: typeof ProtectedAppServerIdIndexRouteImport
      parentRoute: typeof ProtectedAppServerIdLayoutRouteImport
    }
    '/_protected/_app/$serverId/chat/$id': {
      id: '/_protected/_app/$serverId/chat/$id'
      path: '/chat/$id'
      fullPath: '/$serverId/chat/$id'
      preLoaderRoute: typeof ProtectedAppServerIdChatIdRouteImport
      parentRoute: typeof ProtectedAppServerIdLayoutRouteImport
    }
    '/_protected/_app/$serverId/profile/$id': {
      id: '/_protected/_app/$serverId/profile/$id'
      path: '/profile/$id'
      fullPath: '/$serverId/profile/$id'
      preLoaderRoute: typeof ProtectedAppServerIdProfileIdRouteImport
      parentRoute: typeof ProtectedAppServerIdLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProtectedAppServerIdLayoutRouteChildren {
  ProtectedAppServerIdBillingRoute: typeof ProtectedAppServerIdBillingRoute
  ProtectedAppServerIdSettingsRoute: typeof ProtectedAppServerIdSettingsRoute
  ProtectedAppServerIdIndexRoute: typeof ProtectedAppServerIdIndexRoute
  ProtectedAppServerIdChatIdRoute: typeof ProtectedAppServerIdChatIdRoute
  ProtectedAppServerIdProfileIdRoute: typeof ProtectedAppServerIdProfileIdRoute
}

const ProtectedAppServerIdLayoutRouteChildren: ProtectedAppServerIdLayoutRouteChildren =
  {
    ProtectedAppServerIdBillingRoute: ProtectedAppServerIdBillingRoute,
    ProtectedAppServerIdSettingsRoute: ProtectedAppServerIdSettingsRoute,
    ProtectedAppServerIdIndexRoute: ProtectedAppServerIdIndexRoute,
    ProtectedAppServerIdChatIdRoute: ProtectedAppServerIdChatIdRoute,
    ProtectedAppServerIdProfileIdRoute: ProtectedAppServerIdProfileIdRoute,
  }

const ProtectedAppServerIdLayoutRouteWithChildren =
  ProtectedAppServerIdLayoutRoute._addFileChildren(
    ProtectedAppServerIdLayoutRouteChildren,
  )

interface ProtectedAppLayoutRouteChildren {
  ProtectedAppServerIdLayoutRoute: typeof ProtectedAppServerIdLayoutRouteWithChildren
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
}

const ProtectedAppLayoutRouteChildren: ProtectedAppLayoutRouteChildren = {
  ProtectedAppServerIdLayoutRoute: ProtectedAppServerIdLayoutRouteWithChildren,
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
}

const ProtectedAppLayoutRouteWithChildren =
  ProtectedAppLayoutRoute._addFileChildren(ProtectedAppLayoutRouteChildren)

interface ProtectedLayoutRouteChildren {
  ProtectedAppLayoutRoute: typeof ProtectedAppLayoutRouteWithChildren
  ProtectedOnboardingIndexRoute: typeof ProtectedOnboardingIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedAppLayoutRoute: ProtectedAppLayoutRouteWithChildren,
  ProtectedOnboardingIndexRoute: ProtectedOnboardingIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedAppLayoutRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$serverId': typeof ProtectedAppServerIdLayoutRouteWithChildren
  '/': typeof ProtectedAppIndexRoute
  '/onboarding': typeof ProtectedOnboardingIndexRoute
  '/$serverId/billing': typeof ProtectedAppServerIdBillingRoute
  '/$serverId/settings': typeof ProtectedAppServerIdSettingsRoute
  '/$serverId/': typeof ProtectedAppServerIdIndexRoute
  '/$serverId/chat/$id': typeof ProtectedAppServerIdChatIdRoute
  '/$serverId/profile/$id': typeof ProtectedAppServerIdProfileIdRoute
}

export interface FileRoutesByTo {
  '': typeof ProtectedLayoutRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/': typeof ProtectedAppIndexRoute
  '/onboarding': typeof ProtectedOnboardingIndexRoute
  '/$serverId/billing': typeof ProtectedAppServerIdBillingRoute
  '/$serverId/settings': typeof ProtectedAppServerIdSettingsRoute
  '/$serverId': typeof ProtectedAppServerIdIndexRoute
  '/$serverId/chat/$id': typeof ProtectedAppServerIdChatIdRoute
  '/$serverId/profile/$id': typeof ProtectedAppServerIdProfileIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_protected/_app': typeof ProtectedAppLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/_app/$serverId': typeof ProtectedAppServerIdLayoutRouteWithChildren
  '/_protected/_app/': typeof ProtectedAppIndexRoute
  '/_protected/onboarding/': typeof ProtectedOnboardingIndexRoute
  '/_protected/_app/$serverId/billing': typeof ProtectedAppServerIdBillingRoute
  '/_protected/_app/$serverId/settings': typeof ProtectedAppServerIdSettingsRoute
  '/_protected/_app/$serverId/': typeof ProtectedAppServerIdIndexRoute
  '/_protected/_app/$serverId/chat/$id': typeof ProtectedAppServerIdChatIdRoute
  '/_protected/_app/$serverId/profile/$id': typeof ProtectedAppServerIdProfileIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/$serverId'
    | '/'
    | '/onboarding'
    | '/$serverId/billing'
    | '/$serverId/settings'
    | '/$serverId/'
    | '/$serverId/chat/$id'
    | '/$serverId/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/onboarding'
    | '/$serverId/billing'
    | '/$serverId/settings'
    | '/$serverId'
    | '/$serverId/chat/$id'
    | '/$serverId/profile/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_protected/_app'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/_app/$serverId'
    | '/_protected/_app/'
    | '/_protected/onboarding/'
    | '/_protected/_app/$serverId/billing'
    | '/_protected/_app/$serverId/settings'
    | '/_protected/_app/$serverId/'
    | '/_protected/_app/$serverId/chat/$id'
    | '/_protected/_app/$serverId/profile/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_protected"
      ]
    },
    "/_auth": {
      "filePath": "_auth/layout.tsx",
      "children": [
        "/_auth/sign-in",
        "/_auth/sign-up"
      ]
    },
    "/_protected": {
      "filePath": "_protected/layout.tsx",
      "children": [
        "/_protected/_app",
        "/_protected/onboarding/"
      ]
    },
    "/_protected/_app": {
      "filePath": "_protected/_app/layout.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/_app/$serverId",
        "/_protected/_app/"
      ]
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx",
      "parent": "/_auth"
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx",
      "parent": "/_auth"
    },
    "/_protected/_app/$serverId": {
      "filePath": "_protected/_app/$serverId/layout.tsx",
      "parent": "/_protected/_app",
      "children": [
        "/_protected/_app/$serverId/billing",
        "/_protected/_app/$serverId/settings",
        "/_protected/_app/$serverId/",
        "/_protected/_app/$serverId/chat/$id",
        "/_protected/_app/$serverId/profile/$id"
      ]
    },
    "/_protected/_app/": {
      "filePath": "_protected/_app/index.tsx",
      "parent": "/_protected/_app"
    },
    "/_protected/onboarding/": {
      "filePath": "_protected/onboarding/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/_app/$serverId/billing": {
      "filePath": "_protected/_app/$serverId/billing.tsx",
      "parent": "/_protected/_app/$serverId"
    },
    "/_protected/_app/$serverId/settings": {
      "filePath": "_protected/_app/$serverId/settings.tsx",
      "parent": "/_protected/_app/$serverId"
    },
    "/_protected/_app/$serverId/": {
      "filePath": "_protected/_app/$serverId/index.tsx",
      "parent": "/_protected/_app/$serverId"
    },
    "/_protected/_app/$serverId/chat/$id": {
      "filePath": "_protected/_app/$serverId/chat/$id.tsx",
      "parent": "/_protected/_app/$serverId"
    },
    "/_protected/_app/$serverId/profile/$id": {
      "filePath": "_protected/_app/$serverId/profile/$id.tsx",
      "parent": "/_protected/_app/$serverId"
    }
  }
}
ROUTE_MANIFEST_END */
