/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InternalImport } from './routes/internal'
import { Route as AppLayoutImport } from './routes/_app/layout'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppServerIdLayoutImport } from './routes/_app/$serverId/layout'
import { Route as AppServerIdIndexImport } from './routes/_app/$serverId/index'
import { Route as AppServerIdSettingsImport } from './routes/_app/$serverId/settings'
import { Route as AppServerIdBillingImport } from './routes/_app/$serverId/billing'
import { Route as AppServerIdProfileIdImport } from './routes/_app/$serverId/profile/$id'
import { Route as AppServerIdChatTestImport } from './routes/_app/$serverId/chat/test'
import { Route as AppServerIdChatIdImport } from './routes/_app/$serverId/chat/$id'

// Create/Update Routes

const InternalRoute = InternalImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppServerIdLayoutRoute = AppServerIdLayoutImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppServerIdIndexRoute = AppServerIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

const AppServerIdSettingsRoute = AppServerIdSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

const AppServerIdBillingRoute = AppServerIdBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

const AppServerIdProfileIdRoute = AppServerIdProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

const AppServerIdChatTestRoute = AppServerIdChatTestImport.update({
  id: '/chat/test',
  path: '/chat/test',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

const AppServerIdChatIdRoute = AppServerIdChatIdImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppServerIdLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/internal': {
      id: '/internal'
      path: '/internal'
      fullPath: '/internal'
      preLoaderRoute: typeof InternalImport
      parentRoute: typeof rootRoute
    }
    '/_app/$serverId': {
      id: '/_app/$serverId'
      path: '/$serverId'
      fullPath: '/$serverId'
      preLoaderRoute: typeof AppServerIdLayoutImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/$serverId/billing': {
      id: '/_app/$serverId/billing'
      path: '/billing'
      fullPath: '/$serverId/billing'
      preLoaderRoute: typeof AppServerIdBillingImport
      parentRoute: typeof AppServerIdLayoutImport
    }
    '/_app/$serverId/settings': {
      id: '/_app/$serverId/settings'
      path: '/settings'
      fullPath: '/$serverId/settings'
      preLoaderRoute: typeof AppServerIdSettingsImport
      parentRoute: typeof AppServerIdLayoutImport
    }
    '/_app/$serverId/': {
      id: '/_app/$serverId/'
      path: '/'
      fullPath: '/$serverId/'
      preLoaderRoute: typeof AppServerIdIndexImport
      parentRoute: typeof AppServerIdLayoutImport
    }
    '/_app/$serverId/chat/$id': {
      id: '/_app/$serverId/chat/$id'
      path: '/chat/$id'
      fullPath: '/$serverId/chat/$id'
      preLoaderRoute: typeof AppServerIdChatIdImport
      parentRoute: typeof AppServerIdLayoutImport
    }
    '/_app/$serverId/chat/test': {
      id: '/_app/$serverId/chat/test'
      path: '/chat/test'
      fullPath: '/$serverId/chat/test'
      preLoaderRoute: typeof AppServerIdChatTestImport
      parentRoute: typeof AppServerIdLayoutImport
    }
    '/_app/$serverId/profile/$id': {
      id: '/_app/$serverId/profile/$id'
      path: '/profile/$id'
      fullPath: '/$serverId/profile/$id'
      preLoaderRoute: typeof AppServerIdProfileIdImport
      parentRoute: typeof AppServerIdLayoutImport
    }
  }
}

// Create and export the route tree

interface AppServerIdLayoutRouteChildren {
  AppServerIdBillingRoute: typeof AppServerIdBillingRoute
  AppServerIdSettingsRoute: typeof AppServerIdSettingsRoute
  AppServerIdIndexRoute: typeof AppServerIdIndexRoute
  AppServerIdChatIdRoute: typeof AppServerIdChatIdRoute
  AppServerIdChatTestRoute: typeof AppServerIdChatTestRoute
  AppServerIdProfileIdRoute: typeof AppServerIdProfileIdRoute
}

const AppServerIdLayoutRouteChildren: AppServerIdLayoutRouteChildren = {
  AppServerIdBillingRoute: AppServerIdBillingRoute,
  AppServerIdSettingsRoute: AppServerIdSettingsRoute,
  AppServerIdIndexRoute: AppServerIdIndexRoute,
  AppServerIdChatIdRoute: AppServerIdChatIdRoute,
  AppServerIdChatTestRoute: AppServerIdChatTestRoute,
  AppServerIdProfileIdRoute: AppServerIdProfileIdRoute,
}

const AppServerIdLayoutRouteWithChildren =
  AppServerIdLayoutRoute._addFileChildren(AppServerIdLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppServerIdLayoutRoute: typeof AppServerIdLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppServerIdLayoutRoute: AppServerIdLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppLayoutRouteWithChildren
  '/internal': typeof InternalRoute
  '/$serverId': typeof AppServerIdLayoutRouteWithChildren
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/$serverId/billing': typeof AppServerIdBillingRoute
  '/$serverId/settings': typeof AppServerIdSettingsRoute
  '/$serverId/': typeof AppServerIdIndexRoute
  '/$serverId/chat/$id': typeof AppServerIdChatIdRoute
  '/$serverId/chat/test': typeof AppServerIdChatTestRoute
  '/$serverId/profile/$id': typeof AppServerIdProfileIdRoute
}

export interface FileRoutesByTo {
  '/internal': typeof InternalRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/$serverId/billing': typeof AppServerIdBillingRoute
  '/$serverId/settings': typeof AppServerIdSettingsRoute
  '/$serverId': typeof AppServerIdIndexRoute
  '/$serverId/chat/$id': typeof AppServerIdChatIdRoute
  '/$serverId/chat/test': typeof AppServerIdChatTestRoute
  '/$serverId/profile/$id': typeof AppServerIdProfileIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppLayoutRouteWithChildren
  '/internal': typeof InternalRoute
  '/_app/$serverId': typeof AppServerIdLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/$serverId/billing': typeof AppServerIdBillingRoute
  '/_app/$serverId/settings': typeof AppServerIdSettingsRoute
  '/_app/$serverId/': typeof AppServerIdIndexRoute
  '/_app/$serverId/chat/$id': typeof AppServerIdChatIdRoute
  '/_app/$serverId/chat/test': typeof AppServerIdChatTestRoute
  '/_app/$serverId/profile/$id': typeof AppServerIdProfileIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/internal'
    | '/$serverId'
    | '/'
    | '/onboarding'
    | '/$serverId/billing'
    | '/$serverId/settings'
    | '/$serverId/'
    | '/$serverId/chat/$id'
    | '/$serverId/chat/test'
    | '/$serverId/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/internal'
    | '/'
    | '/onboarding'
    | '/$serverId/billing'
    | '/$serverId/settings'
    | '/$serverId'
    | '/$serverId/chat/$id'
    | '/$serverId/chat/test'
    | '/$serverId/profile/$id'
  id:
    | '__root__'
    | '/_app'
    | '/internal'
    | '/_app/$serverId'
    | '/_app/'
    | '/onboarding/'
    | '/_app/$serverId/billing'
    | '/_app/$serverId/settings'
    | '/_app/$serverId/'
    | '/_app/$serverId/chat/$id'
    | '/_app/$serverId/chat/test'
    | '/_app/$serverId/profile/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  InternalRoute: typeof InternalRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  InternalRoute: InternalRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/internal",
        "/onboarding/"
      ]
    },
    "/_app": {
      "filePath": "_app/layout.tsx",
      "children": [
        "/_app/$serverId",
        "/_app/"
      ]
    },
    "/internal": {
      "filePath": "internal.tsx"
    },
    "/_app/$serverId": {
      "filePath": "_app/$serverId/layout.tsx",
      "parent": "/_app",
      "children": [
        "/_app/$serverId/billing",
        "/_app/$serverId/settings",
        "/_app/$serverId/",
        "/_app/$serverId/chat/$id",
        "/_app/$serverId/chat/test",
        "/_app/$serverId/profile/$id"
      ]
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/_app/$serverId/billing": {
      "filePath": "_app/$serverId/billing.tsx",
      "parent": "/_app/$serverId"
    },
    "/_app/$serverId/settings": {
      "filePath": "_app/$serverId/settings.tsx",
      "parent": "/_app/$serverId"
    },
    "/_app/$serverId/": {
      "filePath": "_app/$serverId/index.tsx",
      "parent": "/_app/$serverId"
    },
    "/_app/$serverId/chat/$id": {
      "filePath": "_app/$serverId/chat/$id.tsx",
      "parent": "/_app/$serverId"
    },
    "/_app/$serverId/chat/test": {
      "filePath": "_app/$serverId/chat/test.tsx",
      "parent": "/_app/$serverId"
    },
    "/_app/$serverId/profile/$id": {
      "filePath": "_app/$serverId/profile/$id.tsx",
      "parent": "/_app/$serverId"
    }
  }
}
ROUTE_MANIFEST_END */
