/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalstorageRouteImport } from './routes/localstorage'
import { Route as IndexeddbRouteImport } from './routes/indexeddb'
import { Route as IndexRouteImport } from './routes/index'

const LocalstorageRoute = LocalstorageRouteImport.update({
  id: '/localstorage',
  path: '/localstorage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexeddbRoute = IndexeddbRouteImport.update({
  id: '/indexeddb',
  path: '/indexeddb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexeddb': typeof IndexeddbRoute
  '/localstorage': typeof LocalstorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexeddb': typeof IndexeddbRoute
  '/localstorage': typeof LocalstorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indexeddb': typeof IndexeddbRoute
  '/localstorage': typeof LocalstorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indexeddb' | '/localstorage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indexeddb' | '/localstorage'
  id: '__root__' | '/' | '/indexeddb' | '/localstorage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexeddbRoute: typeof IndexeddbRoute
  LocalstorageRoute: typeof LocalstorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/localstorage': {
      id: '/localstorage'
      path: '/localstorage'
      fullPath: '/localstorage'
      preLoaderRoute: typeof LocalstorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexeddb': {
      id: '/indexeddb'
      path: '/indexeddb'
      fullPath: '/indexeddb'
      preLoaderRoute: typeof IndexeddbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexeddbRoute: IndexeddbRoute,
  LocalstorageRoute: LocalstorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
